name: train-all-notebooks

on:
  push:
    branches: [ main ]

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Install Kaggle CLI
      run: pip install kaggle

    - name: Configure Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        cat <<EOF > ~/.kaggle/kaggle.json
        {
          "username":"${{ secrets.KAGGLE_USERNAME }}",
          "key":"${{ secrets.KAGGLE_KEY }}"
        }
        EOF
        chmod 600 ~/.kaggle/kaggle.json

    - name: Prepare raw data
      run: |
        rm -rf data/raw && mkdir -p data/raw
        kaggle datasets download -d bizzyvinci/coinmarketcap-historical-data -p data/raw/ && \
          unzip -o data/raw/coinmarketcap-historical-data.zip -d data/raw/
        kaggle datasets download -d gautamchettiar/historical-sentiment-data-btc-eth-bnb-ada -p data/raw/ && \
          unzip -o data/raw/historical-sentiment-data-btc-eth-bnb-ada.zip -d data/raw/
        kaggle datasets download -d oliviervha/crypto-news -p data/raw/ && \
          unzip -o data/raw/crypto-news.zip -d data/raw/

    - name: Setup Python & dependencies
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
    - run: |
        pip install papermill pandas seaborn scikit-learn missingno matplotlib \
                    xgboost lightgbm joblib ipykernel ipython-autotime

    - name: Install Jupyter kernel
      run: |
        python -m ipykernel install \
          --sys-prefix \
          --name python3 \
          --display-name python3

    - name: Run Notebook 1:EDA & Preprocessing
      run: |
        mkdir -p reports data/interim
        papermill \
          notebooks/1_eda_preprocessing.ipynb \
          reports/1_eda_preprocessing_output.ipynb \
          -p DATA_RAW data/raw \
          -p DATA_INTERIM data/interim \
          --log-output

    - name: Run Notebook 2:Feature Engineering
      run: |
        mkdir -p reports data/processed
        papermill \
          notebooks/2_feature_engineering.ipynb \
          reports/2_feature_engineering_output.ipynb \
          -p DATA_INTERIM   data/interim \
          -p DATA_PROCESSED data/processed \
          --log-output

    - name: Run Notebook 3:Modeling
      run: |
        mkdir -p reports src/models
        papermill \
          notebooks/3_modeling.ipynb \
          reports/3_modeling_output.ipynb \
          -p DATA_PROCESSED data/processed \
          -p MODEL_DIR src/models \
          --log-output

    - name: Commit & Push outputs
      uses: EndBug/add-and-commit@v7
      with:
        author_name: github-actions[bot]
        author_email: github-actions[bot]@users.noreply.github.com
        message: "ci: update interim/ processed/ models/ reports/"
        add: |
          data/interim/**
          data/processed/**
          src/models/**
          reports/**
        branch: main