name: Always Run Feature Engineering

permissions:
  contents: write

on:
  push: {}

jobs:
  feature_engineering:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install \
            papermill \
            pandas seaborn scikit-learn matplotlib \
            ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install \
            --sys-prefix \
            --name python3 \
            --display-name python3

      - name: Run Notebook 2:Feature Engineering
        run: |
          mkdir -p reports data/processed
          papermill \
            notebooks/2_feature_engineering.ipynb \
            reports/2_feature_engineering_output.ipynb \
            -p DATA_INTERIM   data/interim \
            -p DATA_PROCESSED data/processed \
            --log-output

      - name: Commit & Push FE outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch:        ${{ github.ref_name }}
          commit_user_name:  github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_message: "ci: update processed data & FE report"
          file_pattern:  "."