name: Always Run Modeling

permissions:
  contents: write

on:
  push: {}

jobs:
  modeling:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository (with LFS)
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install \
            papermill \
            pandas seaborn scikit-learn matplotlib \
            xgboost lightgbm joblib \
            ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install \
            --sys-prefix \
            --name python3 \
            --display-name python3

      - name: Run Notebook 3:Modeling
        run: |
          mkdir -p reports src/models
          papermill \
            notebooks/3_modeling.ipynb \
            reports/3_modeling_output.ipynb \
            -p DATA_PROCESSED data/processed \
            -p MODEL_DIR      src/models \
            --log-output

      - name: Commit & Push modeling outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch:           ${{ github.ref_name }}
          commit_user_name:  github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          commit_message:          "ci: update models & modeling report"
          file_pattern:     "."