name: train

permissions:
  contents: write

on:
  push:
    paths:
      - 'notebooks/**'
      - '.github/workflows/train.yml'

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      eda:         ${{ steps.filter.outputs.eda }}
      fe:          ${{ steps.filter.outputs.fe }}
      model:       ${{ steps.filter.outputs.model }}
      sensitivity: ${{ steps.filter.outputs.sensitivity }}
      config:      ${{ steps.filter.outputs.config }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Detect changed notebooks & config
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            eda:
              - 'notebooks/1_eda_preprocessing.ipynb'
            fe:
              - 'notebooks/2_feature_engineering.ipynb'
            model:
              - 'notebooks/3_modeling.ipynb'
            sensitivity:
              - 'notebooks/4_sensitivity.ipynb'
            config:
              - '.github/workflows/train.yml'


  eda:
    needs: check_changes
    if: needs.check_changes.outputs.eda == 'true' || needs.check_changes.outputs.config == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install Kaggle CLI
        run: pip install kaggle

      - name: Configure Kaggle credentials
        run: |
          mkdir -p ~/.kaggle
          cat <<EOF > ~/.kaggle/kaggle.json
          {
            "username":"${{ secrets.KAGGLE_USERNAME }}",
            "key":"${{ secrets.KAGGLE_KEY }}"
          }
          EOF
          chmod 600 ~/.kaggle/kaggle.json

      - name: Download raw datasets
        run: |
          kaggle datasets download -d bizzyvinci/coinmarketcap-historical-data -p data/raw/
          unzip -o data/raw/coinmarketcap-historical-data.zip -d data/raw/
          kaggle datasets download -d gautamchettiar/historical-sentiment-data-btc-eth-bnb-ada -p data/raw/
          unzip -o data/raw/historical-sentiment-data-btc-eth-bnb-ada.zip -d data/raw/
          kaggle datasets download -d oliviervha/crypto-news -p data/raw/
          unzip -o data/raw/crypto-news.zip -d data/raw/

      - name: Setup Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install papermill pandas seaborn scikit-learn missingno matplotlib ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install --sys-prefix --name python3 --display-name python3

      - name: Run Notebook 1:EDA & Preprocessing
        run: |
          mkdir -p data/interim reports
          papermill \
            notebooks/1_eda_preprocessing.ipynb \
            reports/1_eda_preprocessing_output.ipynb \
            -p DATA_RAW     data/raw \
            -p DATA_INTERIM data/interim \
            --log-output

      - name: Commit EDA outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/interim/ reports/1_eda_preprocessing_output.ipynb
          git commit -m "ci: update interim data & EDA report" || echo "No changes"
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}


  fe:
    needs: [check_changes, eda]
    if: needs.check_changes.outputs.fe == 'true' || needs.check_changes.outputs.eda == 'true' || needs.check_changes.outputs.config == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install papermill pandas seaborn scikit-learn matplotlib ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install --sys-prefix --name python3 --display-name python3

      - name: Run Notebook 2:Feature Engineering
        run: |
          mkdir -p data/processed reports
          papermill \
            notebooks/2_feature_engineering.ipynb \
            reports/2_feature_engineering_output.ipynb \
            -p DATA_INTERIM   data/interim \
            -p DATA_PROCESSED data/processed \
            --log-output

      - name: Commit FE outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/processed/ reports/2_feature_engineering_output.ipynb
          git commit -m "ci: update processed data & FE report" || echo "No changes"
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}


  model:
    needs: [check_changes, fe]
    if: needs.check_changes.outputs.model == 'true' || needs.check_changes.outputs.fe == 'true' || needs.check_changes.outputs.eda == 'true' || needs.check_changes.outputs.config == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install papermill pandas seaborn scikit-learn matplotlib xgboost lightgbm joblib ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install --sys-prefix --name python3 --display-name python3

      - name: Run Notebook 3:Modeling
        run: |
          mkdir -p src/models reports
          papermill \
            notebooks/3_modeling.ipynb \
            reports/3_modeling_output.ipynb \
            -p DATA_PROCESSED data/processed \
            -p MODEL_DIR      src/models \
            --log-output

      - name: Commit modeling outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/models/ reports/3_modeling_output.ipynb
          git commit -m "ci: update models & modeling report" || echo "No changes"
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}


  sensitivity:
    needs: [check_changes, model]
    if: needs.check_changes.outputs.sensitivity == 'true' || needs.check_changes.outputs.model == 'true' || needs.check_changes.outputs.fe == 'true' || needs.check_changes.outputs.eda == 'true' || needs.check_changes.outputs.config == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Setup Python & deps
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      - run: pip install papermill pandas seaborn scikit-learn matplotlib joblib ipykernel ipython-autotime

      - name: Install Jupyter kernel
        run: |
          python -m ipykernel install --sys-prefix --name python3 --display-name python3

      - name: Run Notebook 4:Sensitivity Tests
        run: |
          mkdir -p reports
          papermill \
            notebooks/4_sensitivity.ipynb \
            reports/4_sensitivity_output.ipynb \
            -p DATA_PROCESSED data/processed \
            -p MODEL_DIR      src/models \
            --log-output

      - name: Commit sensitivity report
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/4_sensitivity_output.ipynb
          git commit -m "ci: update sensitivity report" || echo "No changes"
          git pull --rebase --autostash origin ${{ github.ref_name }}
          git push origin HEAD:${{ github.ref_name }}
